% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Feb-2015 20:46:19
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
                                 

kb = Simulink.Parameter;
kb.Value = 1;
kb.CoderInfo.StorageClass = 'Auto';
kb.CoderInfo.Alias = '';
kb.CoderInfo.Alignment = -1;
kb.CoderInfo.CustomStorageClass = 'Default';
%kb.CoderInfo.CustomAttributes.ConcurrentAccess = false;
kb.Description = 'Brake Resistance';
kb.DataType = 'auto';
kb.Min = [];
kb.Max = [];
kb.DocUnits = '';

ub = Simulink.Parameter;
ub.Value = 1;
ub.CoderInfo.StorageClass = 'Auto';
ub.CoderInfo.Alias = '';
ub.CoderInfo.Alignment = -1;
ub.CoderInfo.CustomStorageClass = 'Default';
%ub.CoderInfo.CustomAttributes.ConcurrentAccess = false;
ub.Description = ['converstion from % brake to force apply', char(10), ''];
ub.DataType = 'auto';
ub.Min = [];
ub.Max = [];
ub.DocUnits = 'N/%';

save('RW3_Brakes.mat','kb','ub');