% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Feb-2015 22:40:20
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
                                

At = Simulink.Parameter;
At.Value = -2.0696413137607281E-5;
At.CoderInfo.StorageClass = 'Auto';
At.CoderInfo.Alias = '';
At.CoderInfo.Alignment = -1;
At.CoderInfo.CustomStorageClass = 'Default';
At.CoderInfo.CustomAttributes.ConcurrentAccess = false;
At.Description = 'Tire Radius A constant';
At.DataType = 'auto';
At.Min = [];
At.Max = [];
At.DocUnits = '';

Bk = Simulink.Parameter;
Bk.Value = 10;
Bk.CoderInfo.StorageClass = 'Auto';
Bk.CoderInfo.Alias = '';
Bk.CoderInfo.Alignment = -1;
Bk.CoderInfo.CustomStorageClass = 'Default';
Bk.CoderInfo.CustomAttributes.ConcurrentAccess = false;
Bk.Description = 'B magic number';
Bk.DataType = 'auto';
Bk.Min = [];
Bk.Max = [];
Bk.DocUnits = '';

Bt = Simulink.Parameter;
Bt.Value = 6.386679031823E-6;
Bt.CoderInfo.StorageClass = 'Auto';
Bt.CoderInfo.Alias = '';
Bt.CoderInfo.Alignment = -1;
Bt.CoderInfo.CustomStorageClass = 'Default';
Bt.CoderInfo.CustomAttributes.ConcurrentAccess = false;
Bt.Description = 'Tire Radius B constant';
Bt.DataType = 'auto';
Bt.Min = [];
Bt.Max = [];
Bt.DocUnits = '';

Ck = Simulink.Parameter;
Ck.Value = 1.9;
Ck.CoderInfo.StorageClass = 'Auto';
Ck.CoderInfo.Alias = '';
Ck.CoderInfo.Alignment = -1;
Ck.CoderInfo.CustomStorageClass = 'Default';
Ck.CoderInfo.CustomAttributes.ConcurrentAccess = false;
Ck.Description = '';
Ck.DataType = 'auto';
Ck.Min = [];
Ck.Max = [];
Ck.DocUnits = '';

Ct = Simulink.Parameter;
Ct.Value = 0.317;
Ct.CoderInfo.StorageClass = 'Auto';
Ct.CoderInfo.Alias = '';
Ct.CoderInfo.Alignment = -1;
Ct.CoderInfo.CustomStorageClass = 'Default';
Ct.CoderInfo.CustomAttributes.ConcurrentAccess = false;
Ct.Description = ['tire Radius C constant', char(10), ''];
Ct.DataType = 'auto';
Ct.Min = [];
Ct.Max = [];
Ct.DocUnits = 'Bar';

Dk = Simulink.Parameter;
Dk.Value = 1;
Dk.CoderInfo.StorageClass = 'Auto';
Dk.CoderInfo.Alias = '';
Dk.CoderInfo.Alignment = -1;
Dk.CoderInfo.CustomStorageClass = 'Default';
Dk.CoderInfo.CustomAttributes.ConcurrentAccess = false;
Dk.Description = 'Magic D';
Dk.DataType = 'auto';
Dk.Min = [];
Dk.Max = [];
Dk.DocUnits = '';

Ek = Simulink.Parameter;
Ek.Value = 0.97;
Ek.CoderInfo.StorageClass = 'Auto';
Ek.CoderInfo.Alias = '';
Ek.CoderInfo.Alignment = -1;
Ek.CoderInfo.CustomStorageClass = 'Default';
Ek.CoderInfo.CustomAttributes.ConcurrentAccess = false;
Ek.Description = 'Magic E';
Ek.DataType = 'auto';
Ek.Min = [];
Ek.Max = [];
Ek.DocUnits = '';

pt = Simulink.Parameter;
pt.Value = 3;
pt.CoderInfo.StorageClass = 'Auto';
pt.CoderInfo.Alias = '';
pt.CoderInfo.Alignment = -1;
pt.CoderInfo.CustomStorageClass = 'Default';
pt.CoderInfo.CustomAttributes.ConcurrentAccess = false;
pt.Description = 'Tire Preasure';
pt.DataType = 'auto';
pt.Min = [];
pt.Max = [];
pt.DocUnits = 'bar';

rb = Simulink.Parameter;
rb.Value = 0.1;
rb.CoderInfo.StorageClass = 'Auto';
rb.CoderInfo.Alias = '';
rb.CoderInfo.Alignment = -1;
rb.CoderInfo.CustomStorageClass = 'Default';
rb.CoderInfo.CustomAttributes.ConcurrentAccess = false;
rb.Description = 'Brake Caliber Radius';
rb.DataType = 'auto';
rb.Min = [];
rb.Max = [];
rb.DocUnits = 'm';

save('RW3_Tires.mat','rb','pt','Ek','Ck','Bk','Ak', 'Dk','At','Bt','Ct');
