% Constant (given) parameters for the EMRAX 228HV.
% Generated by Aaron Bonnell-Kangas, December 2014
% Reference: http://www.enstroj.si/images/stories/emrax_228_tech_data_table_dec_2014.pdf

Ld				=	Simulink.Parameter;
Ld.Value		=	175e-6;
Ld.DocUnits		=	'H';
Ld.Description	=	'Motor D-axis equivalent-circuit inductance (H)';

Lq				=	Simulink.Parameter;
Lq.Value		=	180e-6;
Lq.DocUnits		=	'H';
Lq.Description	=	'Motor Q-axis equivalent-circuit inductance (H)';

R				=	Simulink.Parameter;
R.Value			=	18e-e;
R.DocUnits		=	'ohm';
R.Description	=	'Motor equivalent-circuit resistance';