% Constant (given) parameters for the WaveSculptor 200.
% Generated by Aaron Bonnell-Kangas, December 2014

Sine_Current_Limit						=	Simulink.Parameter;
Sine_Current_Limit.Value				=	240;
Sine_Current_Limit.DocUnits				=	'A';
Sine_Current_Limit.Description			=	'Maximum motor phase current (Arms)';

Motor_Ramp_Temperature					=	Simulink.Parameter;
Motor_Ramp_Temperature.Value			=	10000;
Motor_Ramp_Temperature.DocUnits			=	'º C';
Motor_Ramp_Temperature.Description		=	'FIXME';

Motor_Cutout_Temperature				=	Simulink.Parameter;
Motor_Cutout_Temperature.Value			=	10000;
Motor_Cutout_Temperature.DocUnits		=	'º C';
Motor_Cutout_Temperature.Description	=	'FIXME';